#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
"""
Scaffold a new Agent Skill directory conforming to the agentskills.io spec.

Usage:
    uv run scripts/scaffold.py --name <name> --description <text> [OPTIONS]

Exit codes:
    0  Success
    1  Invalid arguments or validation error
    2  Output directory already exists (use --force to overwrite)
"""

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

NAME_RE = re.compile(r'^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')


def validate_name(name: str) -> str | None:
    """Return error message or None if valid."""
    if not name:
        return "name cannot be empty"
    if len(name) > 64:
        return f"name exceeds 64 chars (got {len(name)}): {name!r}"
    if not NAME_RE.match(name):
        return (
            f"name {name!r} is invalid: must be lowercase alphanumeric + hyphens, "
            "no leading/trailing/consecutive hyphens. Example: 'my-skill'"
        )
    if "--" in name:
        return f"name {name!r} contains consecutive hyphens"
    return None


def validate_description(desc: str) -> str | None:
    """Return error message or None if valid."""
    if not desc:
        return "description cannot be empty"
    if len(desc) > 1024:
        return f"description exceeds 1024 chars (got {len(desc)})"
    return None


# ---------------------------------------------------------------------------
# Content generators
# ---------------------------------------------------------------------------

SKILL_MD_TEMPLATE = """\
---
name: {name}
description: >
  {description_wrapped}
license: {license}{compatibility_block}{metadata_block}{allowed_tools_block}
---

# {title}

<!-- TODO: Replace this section with skill instructions. -->

## Overview

Describe what this skill does and what it produces.

## Usage

Describe how to invoke this skill and what inputs it expects.

## Workflow

1. Step one
2. Step two
3. Step three
"""

EXAMPLE_SCRIPT = """\
#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
\"\"\"
Example script for {name}.

Usage:
    uv run scripts/example.py [--help] [--json]

Exit codes:
    0  Success
    1  Error
\"\"\"

import argparse
import json
import sys


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Example script -- replace with real implementation.",
    )
    parser.add_argument("--json", action="store_true", help="Output JSON")
    args = parser.parse_args()

    result = {{"status": "ok", "message": "Hello from {name}"}}

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(result["message"])

    return 0


if __name__ == "__main__":
    sys.exit(main())
"""

EXAMPLE_REFERENCE = """\
# Reference: {name}

<!-- TODO: Replace with actual reference material. -->

This file provides supplementary reference material for `{name}`.
Load this file (Tier 3) only when the agent needs detailed reference
information during execution.

## Section 1

Content here.

## Section 2

Content here.
"""

EXAMPLE_ASSET = """\
---
name: example-skill
description: >
  Example skill description. Use when asked to do example things.
license: Apache-2.0
---

# Example Skill

This is a minimal example skill generated by gastown-admin-skill.
Replace this content with your skill's instructions.
"""


def build_skill_md(args: argparse.Namespace) -> str:
    # Wrap description for YAML block scalar (72-char lines, 2-space indent)
    desc_lines = textwrap.wrap(args.description, width=70)
    if len(desc_lines) == 1:
        description_wrapped = desc_lines[0]
    else:
        description_wrapped = desc_lines[0] + "\n  " + "\n  ".join(desc_lines[1:])

    title = " ".join(w.capitalize() for w in args.name.split("-"))

    compatibility_block = ""
    if args.compatibility:
        compatibility_block = f"\ncompatibility: {args.compatibility}"

    metadata_block = ""
    if args.author or args.version:
        lines = ["\nmetadata:"]
        if args.author:
            lines.append(f"  author: {args.author}")
        if args.version:
            lines.append(f'  version: "{args.version}"')
        metadata_block = "\n".join(lines)

    allowed_tools_block = ""
    if args.allowed_tools:
        allowed_tools_block = f"\nallowed-tools: {args.allowed_tools}"

    return SKILL_MD_TEMPLATE.format(
        name=args.name,
        description_wrapped=description_wrapped,
        license=args.license,
        title=title,
        compatibility_block=compatibility_block,
        metadata_block=metadata_block,
        allowed_tools_block=allowed_tools_block,
    )


# ---------------------------------------------------------------------------
# Scaffolding logic
# ---------------------------------------------------------------------------

def plan_files(args: argparse.Namespace, output_dir: Path) -> list[tuple[Path, str]]:
    """Return list of (path, content) pairs to create."""
    files: list[tuple[Path, str]] = []
    skill_dir = output_dir / args.name

    skill_md_content = build_skill_md(args)
    files.append((skill_dir / "SKILL.md", skill_md_content))

    if args.scripts:
        files.append((
            skill_dir / "scripts" / "example.py",
            EXAMPLE_SCRIPT.format(name=args.name),
        ))

    if args.references:
        files.append((
            skill_dir / "references" / "reference.md",
            EXAMPLE_REFERENCE.format(name=args.name),
        ))

    if args.assets:
        files.append((
            skill_dir / "assets" / "skill-template" / "SKILL.md",
            EXAMPLE_ASSET,
        ))
        files.append((
            skill_dir / "assets" / "examples" / "minimal-skill.md",
            EXAMPLE_ASSET,
        ))

    return files


def scaffold(args: argparse.Namespace) -> tuple[bool, str, list[str]]:
    """
    Execute scaffolding. Returns (success, skill_path, files_created).
    """
    output_dir = Path(args.output).resolve()
    skill_dir = output_dir / args.name

    if skill_dir.exists() and not args.force:
        return False, str(skill_dir), []

    planned = plan_files(args, output_dir)

    if args.dry_run:
        return True, str(skill_dir), [str(p) for p, _ in planned]

    created: list[str] = []
    for path, content in planned:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(str(path))

    return True, str(skill_dir), created


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a new Agent Skill directory (agentskills.io spec).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exit codes:
  0  Skill directory created successfully
  1  Invalid arguments or validation error
  2  Output directory already exists (use --force to overwrite)

Examples:
  uv run scripts/scaffold.py --name my-skill --description "Does X. Use when Y."
  uv run scripts/scaffold.py --name my-skill --description "..." --scripts --references
  uv run scripts/scaffold.py --name my-skill --description "..." --dry-run --json
  uv run scripts/scaffold.py --name my-skill --description "..." --output ~/skills
""",
    )
    parser.add_argument("--name", required=True, help="Skill name (kebab-case, 1-64 chars)")
    parser.add_argument("--description", required=True, help="Skill description (1-1024 chars)")
    parser.add_argument("--license", default="Apache-2.0", help="License identifier [default: Apache-2.0]")
    parser.add_argument("--compatibility", default="", help="Compatibility string (max 500 chars)")
    parser.add_argument("--author", default="", help="Author name for metadata block")
    parser.add_argument("--version", default="", help="Version string for metadata block")
    parser.add_argument("--allowed-tools", default="", dest="allowed_tools",
                        help="Space-delimited allowed tools string")
    parser.add_argument("--scripts", action="store_true", help="Include scripts/ with example.py")
    parser.add_argument("--references", action="store_true", help="Include references/ with reference.md")
    parser.add_argument("--assets", action="store_true", help="Include assets/ with template and example")
    parser.add_argument("--output", default=".", help="Parent directory for new skill [default: .]")
    parser.add_argument("--force", action="store_true", help="Overwrite existing skill directory")
    parser.add_argument("--dry-run", action="store_true", dest="dry_run",
                        help="Show what would be created without writing files")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    args = parser.parse_args()

    # Validate inputs before touching the filesystem
    name_err = validate_name(args.name)
    if name_err:
        if args.json:
            print(json.dumps({"success": False, "error": name_err}))
        else:
            print(f"Error: {name_err}", file=sys.stderr)
        return 1

    desc_err = validate_description(args.description)
    if desc_err:
        if args.json:
            print(json.dumps({"success": False, "error": desc_err}))
        else:
            print(f"Error: {desc_err}", file=sys.stderr)
        return 1

    if args.compatibility and len(args.compatibility) > 500:
        err = f"compatibility exceeds 500 chars (got {len(args.compatibility)})"
        if args.json:
            print(json.dumps({"success": False, "error": err}))
        else:
            print(f"Error: {err}", file=sys.stderr)
        return 1

    output_dir = Path(args.output).resolve()
    skill_dir = output_dir / args.name

    if skill_dir.exists() and not args.force and not args.dry_run:
        err = f"Skill directory already exists: {skill_dir}. Use --force to overwrite."
        if args.json:
            print(json.dumps({"success": False, "error": err, "path": str(skill_dir)}))
        else:
            print(f"Error: {err}", file=sys.stderr)
        return 2

    success, path, files = scaffold(args)

    if args.json:
        payload: dict = {
            "success": success,
            "path": path,
            "files": files,
            "dry_run": args.dry_run,
        }
        print(json.dumps(payload, indent=2))
    else:
        if args.dry_run:
            print(f"Dry run — would create: {path}")
        else:
            print(f"Created: {path}")
        for f in files:
            prefix = "  (dry) " if args.dry_run else "  "
            print(f"{prefix}{f}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
